### ISSUE TITLE
Gradient example not working

### ISSUE THREAD

**Issue by alexfertel** [Ogeon/palette#260]
The gradient example is not working out of the box.

## How To Reproduce

I set up a new cargo binary app and copy-pasted the gradient example. It displays a compilation error.

## Expected Outcome

The example should work.

## Actual Outcome

The example displays a compilation error.

## Additional Details

```toml
# Cargo.toml
[package]
name = "test"
version = "0.1.0"
edition = "2021"

[dependencies]
palette = "0.6.0"
image = "0.23.14"
```

Both stable and nightly rust versions (1.55.0 and 1.57.0).

I use Ubuntu 18.04.
* Cargo.toml entry: 
* Rust version(s): 
* Target platform:
